
image: python:3.5

services:
  - postgres:latest

variables:
  POSTGRES_DB: trashr
  POSTGRES_USER: nick
  POSTGRES_PASSWORD: "$DATABASE_PASSWORD"

# Install reqs before every stage
before_script:
  - pip3 install -r requirements.txt

# Run all tests with coverage
test:
  script:
  - python3 manage.py collectstatic --no-input  # whitenoise requires collectstatic for tests
  - coverage run manage.py test
  - coverage report -m
