# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 20:15
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dumpster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('rfid', models.CharField(default='', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('capacity_units', models.CharField(default='', max_length=20)),
                ('container_type', models.CharField(default='', max_length=50)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, max_digits=12), size=None)),
                ('functioning', models.BooleanField(default=True)),
                ('utility', models.PositiveSmallIntegerField(default=0)),
                ('percent_fill', models.SmallIntegerField(default=0)),
                ('alert_percentage', models.SmallIntegerField(default=70)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('alert_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IntervalReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_reading', models.SmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dumpster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trashr.Dumpster')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dumpster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trashr.Dumpster')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time_estimate', models.PositiveSmallIntegerField()),
                ('number_of_dumpsters', models.IntegerField()),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=8, max_digits=12), size=None), size=None)),
                ('dumpsters', models.ManyToManyField(to='trashr.Dumpster')),
            ],
        ),
        migrations.CreateModel(
            name='UniEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('affected_dumpsters', models.ManyToManyField(to='trashr.Dumpster')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trashr.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dumpster',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trashr.Organization'),
        ),
    ]
