# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='dumpsters',
        ),
        migrations.RemoveField(
            model_name='unievent',
            name='affected_dumpsters',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='UniEvent',
        ),
    ]
