# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0002_auto_20180103_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
