# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0005_auto_20180128_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dumpster',
            old_name='coreid',
            new_name='core_id',
        ),
    ]
