# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0006_auto_20180128_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
