# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-04 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0007_userprofile_email_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='conlon0121@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
