# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0008_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_percent', models.PositiveSmallIntegerField(default=70)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Dumpster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trashr.Dumpster')),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.AddField(
            model_name='organization',
            name='head_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trashr.UserProfile'),
        ),
    ]
