# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0011_alert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='Dumpster',
            new_name='dumpster',
        ),
    ]
