# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0014_auto_20180211_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='org',
        ),
    ]
