# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0015_remove_alert_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(default='', max_length=30)),
                ('source', models.CharField(default='', max_length=50)),
                ('card_type', models.CharField(default='', max_length=20)),
                ('last_four_digits', models.CharField(default='', max_length=20)),
                ('expires', models.DateField()),
                ('default', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='trashr.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('plan_id', models.CharField(default='', max_length=30)),
                ('charge_frequency', models.IntegerField(default=1)),
                ('charge_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('product_id', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(default='', max_length=30)),
                ('charge_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('sensor_count', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='dumpster',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trashr.Organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trashr.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trashr.Product'),
        ),
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trashr.Product'),
        ),
    ]
