# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0016_auto_20180509_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_id',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
    ]
