# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0018_auto_20180509_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='charge_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='charge_date',
            field=models.SmallIntegerField(default=1),
        ),
    ]
