# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0020_auto_20180510_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='source',
        ),
    ]
