# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0022_auto_20180510_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('filled_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='subscription',
            name='charge_date',
            field=models.SmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trashr.Subscription'),
        ),
    ]
