# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trashr', '0023_auto_20180511_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription_string',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='trashr.Subscription'),
        ),
    ]
