# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 22:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dumpster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('rfid', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('capacity_units', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('container_type', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True)),
                ('functioning', models.BooleanField(default=True)),
                ('utility', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IntervalReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_reading', models.IntegerField(default=0)),
                ('percent_fill', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dumpster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Dumpster')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UniEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('affected_dumpsters', models.ManyToManyField(to='base.Dumpster')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dumpster',
            name='org',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
    ]
