# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_reading', models.IntegerField(default=0)),
                ('percent_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='dumpster',
            name='percent_capacity',
        ),
        migrations.AddField(
            model_name='dumpster',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='dumpster',
            name='latitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='dumpster',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='intervalreading',
            name='dumpster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Dumpster'),
        ),
    ]
