# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intervalreading',
            old_name='percent_capacity',
            new_name='percent_fill',
        ),
        migrations.AddField(
            model_name='dumpster',
            name='utility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='capacity_units',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='container_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='org',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='rfid',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
