# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervalreading',
            name='percent_fill',
            field=models.IntegerField(),
        ),
    ]
