# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-28 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170419_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('affected_dumpsters', models.ManyToManyField(to='base.Dumpster')),
            ],
        ),
    ]
