# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20171024_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalreading',
            name='percent_fill',
        ),
        migrations.AddField(
            model_name='dumpster',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dumpster',
            name='percent_fill',
            field=models.IntegerField(default=0),
        ),
    ]
