# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170927_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dumpster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Dumpster')),
            ],
        ),
        migrations.RemoveField(
            model_name='intervalreading',
            name='dumpster',
        ),
        migrations.RemoveField(
            model_name='intervalreading',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='intervalreading',
            name='interval_set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.IntervalSet'),
            preserve_default=False,
        ),
    ]
