# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170831_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpster',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
    ]
