# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20171120_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dumpster',
            old_name='lat_long',
            new_name='coordinates',
        ),
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
