# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170913_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpster',
            name='rfid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
