# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20171121_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='dumpsters',
            field=models.ManyToManyField(to='base.Dumpster'),
        ),
    ]
