# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_route_dumpsters'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpster',
            name='alert_percentage',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='capacity_units',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='container_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='rfid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
