# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20171220_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default='conlon0121@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
