# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_organization_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dumpster',
            name='alert_percentage',
            field=models.SmallIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='percent_fill',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dumpster',
            name='utility',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intervalreading',
            name='raw_reading',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='time_estimate',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
