# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20171228_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(default='', max_length=5),
        ),
    ]
